import { StyleSheet } from "react-native";
export default StyleSheet.create({
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 30,
        backgroundColor: '#ffffff',
    },
    iconWrapper: {
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    unauthTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#000000',
        marginBottom: 12,
        textAlign: 'center',
    },
    unauthSubtitle: {
        fontSize: 14,
        color: '#6c757d',
        textAlign: 'center',
        paddingHorizontal: 15,
        lineHeight: 22,
        marginBottom: 35,
    },
    btnPrimary: {
        backgroundColor: '#1976d2',
        width: '100%',
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnPrimaryText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    btnSecondary: {
        backgroundColor: '#f8f9fa',
        borderWidth: 1,
        borderColor: '#dee2e6',
        width: '100%',
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 12,
    },
    btnSecondaryText: {
        color: '#1976d2',
        fontSize: 16,
        fontWeight: 'bold',
    },
    // Premium Login Screen Styles
    loginContainer: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    loginScrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 30,
    },
    logoWrapper: {
        alignItems: 'center',
        marginBottom: 24,
    },
    logoCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#1976d2',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
        shadowColor: '#1976d2',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 4,
    },
    appName: {
        fontSize: 26,
        fontWeight: 'bold',
        color: '#212529',
        marginBottom: 4,
    },
    appSubtitle: {
        fontSize: 14,
        color: '#6c757d',
    },
    loginCard: {
        backgroundColor: '#ffffff',
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
        width: '100%',
        marginBottom: 20,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#212529',
        marginBottom: 20,
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#495057',
        marginBottom: 6,
    },
    paperInput: {
        backgroundColor: '#ffffff',
    },
    btnLogin: {
        backgroundColor: '#1976d2',
        paddingVertical: 4,
        borderRadius: 8,
        marginTop: 10,
    },
    btnLoginLabel: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#ffffff',
    },
    registerLinkWrapper: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 15,
        marginBottom: 25,
    },
    registerText: {
        fontSize: 14,
        color: '#495057',
    },
    registerLink: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1976d2',
    },
    hintCard: {
        backgroundColor: '#f1f3f5',
        borderRadius: 12,
        padding: 15,
        width: '100%',
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    hintTitle: {
        fontSize: 13,
        fontWeight: 'bold',
        color: '#495057',
        marginBottom: 6,
        textAlign: 'center',
    },
    hintText: {
        fontSize: 12,
        color: '#6c757d',
        lineHeight: 18,
        textAlign: 'center',
    },
    errText: {
        marginBottom: 10,
        textAlign: 'center',
    },
    // Google Sign-in & Divider styles
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 16,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#dee2e6',
    },
    dividerText: {
        marginHorizontal: 10,
        color: '#6c757d',
        fontSize: 13,
    },
    btnGoogle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#dee2e6',
        borderRadius: 8,
        paddingVertical: 12,
        width: '100%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    btnGoogleText: {
        color: '#212529',
        fontSize: 15,
        fontWeight: 'bold',
        marginLeft: 10,
    },
    // Profile Authenticated Dashboard Styles
    profileContainer: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    profileScroll: {
        flexGrow: 1,
        paddingBottom: 40,
    },
    headerCard: {
        backgroundColor: '#ffffff',
        paddingVertical: 30,
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#e9ecef',
        marginBottom: 20,
    },
    avatarCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#adb5bd',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    headerEmail: {
        fontSize: 16,
        color: '#495057',
        fontWeight: '500',
        marginBottom: 12,
    },
    badgeStudent: {
        backgroundColor: '#1976d2',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
    },
    badgeInstructor: {
        backgroundColor: '#2e7d32',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
    },
    badgeAdmin: {
        backgroundColor: '#c62828',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
    },
    badgeText: {
        color: '#ffffff',
        fontSize: 11,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    sectionWrapper: {
        paddingHorizontal: 16,
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#212529',
        marginBottom: 10,
    },
    cardPortal: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#e9ecef',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
    },
    portalTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#212529',
        marginBottom: 6,
    },
    portalSubtitle: {
        fontSize: 13,
        color: '#6c757d',
        lineHeight: 18,
        marginBottom: 16,
    },
    btnApply: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f1f3f5',
        borderRadius: 8,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#dee2e6',
    },
    btnApplyText: {
        color: '#1976d2',
        fontSize: 14,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    listCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e9ecef',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
    },
    listHeader: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#212529',
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
        backgroundColor: '#ffffff',
    },
    listItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f3f5',
        backgroundColor: '#ffffff',
    },
    listItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    listItemText: {
        fontSize: 14,
        color: '#495057',
        marginLeft: 12,
        fontWeight: '500',
    },
    btnLogoutOuter: {
        paddingHorizontal: 16,
        marginTop: 10,
        marginBottom: 20,
    },
    btnLogout: {
        borderWidth: 1,
        borderColor: '#dc3545',
        borderRadius: 8,
        paddingVertical: 14,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#ffffff',
    },
    btnLogoutText: {
        color: '#dc3545',
        fontSize: 15,
        fontWeight: 'bold',
    },
    headerName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#212529',
        marginBottom: 4,
    },
    avatarEditBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: '#1976d2',
        width: 26,
        height: 26,
        borderRadius: 13,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#ffffff',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContainer: {
        backgroundColor: '#ffffff',
        width: '100%',
        maxWidth: 400,
        borderRadius: 16,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 5,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#212529',
    },
    modalInputGroup: {
        marginBottom: 16,
    },
    modalLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#495057',
        marginBottom: 6,
    },
    modalInput: {
        backgroundColor: '#ffffff',
    },
    modalBtnGroup: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 10,
        gap: 12,
    },
    modalBtnCancel: {
        borderColor: '#dee2e6',
    },
    modalBtnSubmit: {
        backgroundColor: '#1976d2',
    },
    avatarSelectContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 20,
    },
    avatarSelectCircle: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#f1f3f5',
        borderWidth: 2,
        borderColor: '#1976d2',
        borderStyle: 'dashed',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        position: 'relative',
    },
    avatarSelectImage: {
        width: '100%',
        height: '100%',
    },
    avatarSelectPlaceholder: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarSelectPlaceholderText: {
        fontSize: 12,
        color: '#1976d2',
        marginTop: 6,
        fontWeight: '600',
    },
    switchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: '#f1f3f5',
        marginTop: 8,
        marginBottom: 16,
    },
    switchLabelContainer: {
        flex: 1,
        paddingRight: 12,
    },
    switchTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#212529',
    },
    switchSubtitle: {
        fontSize: 12,
        color: '#6c757d',
        marginTop: 4,
        lineHeight: 16,
    },
});