import { StyleSheet } from "react-native";
import GlobalStyles from "../../styles/Styles";
import theme from "../../styles/theme";

const localStyles = StyleSheet.create({
    centerContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 30,
        backgroundColor: theme.colors.white,
    },
    iconWrapper: {
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    unauthTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#000000',
        marginBottom: 12,
        textAlign: 'center',
    },
    unauthSubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        textAlign: 'center',
        paddingHorizontal: 15,
        lineHeight: 22,
        marginBottom: 35,
    },
    btnPrimary: {
        backgroundColor: theme.colors.primary,
        width: '100%',
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnPrimaryText: {
        color: theme.colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    btnSecondary: {
        backgroundColor: theme.colors.secondary,
        borderWidth: 1,
        borderColor: theme.colors.border,
        width: '100%',
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 12,
    },
    btnSecondaryText: {
        color: theme.colors.primary,
        fontSize: 16,
        fontWeight: 'bold',
    },
    loginContainer: {
        flex: 1,
        backgroundColor: theme.colors.secondary,
    },
    loginScrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 30,
    },
    logoWrapper: {
        alignItems: 'center',
        marginBottom: 24,
    },
    logoCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 4,
    },
    appName: {
        fontSize: 26,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 4,
    },
    appSubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
    },
    loginCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
        width: '100%',
        marginBottom: 20,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 20,
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        marginBottom: 6,
    },
    paperInput: {
        backgroundColor: theme.colors.white,
    },
    btnLogin: {
        backgroundColor: theme.colors.primary,
        paddingVertical: 4,
        borderRadius: 8,
        marginTop: 10,
    },
    btnLoginLabel: {
        fontSize: 15,
        fontWeight: 'bold',
        color: theme.colors.white,
    },
    registerLinkWrapper: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 15,
        marginBottom: 25,
    },
    registerText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
    },
    registerLink: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.colors.primary,
    },
    hintCard: {
        backgroundColor: '#f1f3f5',
        borderRadius: 12,
        padding: 15,
        width: '100%',
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    hintTitle: {
        fontSize: 13,
        fontWeight: 'bold',
        color: theme.colors.textSecondary,
        marginBottom: 6,
        textAlign: 'center',
    },
    hintText: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        lineHeight: 18,
        textAlign: 'center',
    },
    errText: {
        marginBottom: 10,
        textAlign: 'center',
    },
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 16,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: theme.colors.border,
    },
    dividerText: {
        marginHorizontal: 10,
        color: theme.colors.textSecondary,
        fontSize: 13,
    },
    btnGoogle: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.white,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 8,
        paddingVertical: 12,
        width: '100%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    btnGoogleText: {
        color: theme.colors.text,
        fontSize: 15,
        fontWeight: 'bold',
        marginLeft: 10,
    },
    profileContainer: {
        flex: 1,
        backgroundColor: theme.colors.secondary,
    },
    profileScroll: {
        flexGrow: 1,
        paddingBottom: 40,
    },
    headerCard: {
        backgroundColor: theme.colors.white,
        paddingVertical: 30,
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
        marginBottom: 20,
    },
    avatarCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#adb5bd',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 12,
    },
    headerEmail: {
        fontSize: 16,
        color: theme.colors.textSecondary,
        fontWeight: '500',
        marginBottom: 12,
    },
    badgeStudent: {
        backgroundColor: theme.colors.primary,
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
    },
    badgeInstructor: {
        backgroundColor: theme.colors.success,
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
    },
    badgeAdmin: {
        backgroundColor: theme.colors.danger,
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
    },
    badgeText: {
        color: theme.colors.white,
        fontSize: 11,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    sectionWrapper: {
        paddingHorizontal: 16,
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 10,
    },
    cardPortal: {
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: theme.colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
    },
    portalTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 6,
    },
    portalSubtitle: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        lineHeight: 18,
        marginBottom: 16,
    },
    btnApply: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f1f3f5',
        borderRadius: 8,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    btnApplyText: {
        color: theme.colors.primary,
        fontSize: 14,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    listCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.border,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
    },
    listHeader: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.colors.text,
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 8,
        backgroundColor: theme.colors.white,
    },
    listItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f3f5',
        backgroundColor: theme.colors.white,
    },
    listItemLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    listItemText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        marginLeft: 12,
        fontWeight: '500',
    },
    btnLogoutOuter: {
        paddingHorizontal: 16,
        marginTop: 10,
        marginBottom: 20,
    },
    btnLogout: {
        borderWidth: 1,
        borderColor: theme.colors.danger,
        borderRadius: 8,
        paddingVertical: 14,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.white,
    },
    btnLogoutText: {
        color: theme.colors.danger,
        fontSize: 15,
        fontWeight: 'bold',
    },
    headerName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 4,
    },
    avatarEditBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: theme.colors.primary,
        width: 26,
        height: 26,
        borderRadius: 13,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: theme.colors.white,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContainer: {
        backgroundColor: theme.colors.white,
        width: '100%',
        maxWidth: 400,
        borderRadius: 16,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 5,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    modalInputGroup: {
        marginBottom: 16,
    },
    modalLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textSecondary,
        marginBottom: 6,
    },
    modalInput: {
        backgroundColor: theme.colors.white,
    },
    modalBtnGroup: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 10,
        gap: 12,
    },
    modalBtnCancel: {
        borderColor: theme.colors.border,
    },
    modalBtnSubmit: {
        backgroundColor: theme.colors.primary,
    },
    avatarSelectContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 20,
    },
    avatarSelectCircle: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#f1f3f5',
        borderWidth: 2,
        borderColor: theme.colors.primary,
        borderStyle: 'dashed',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        position: 'relative',
    },
    avatarSelectImage: {
        width: '100%',
        height: '100%',
    },
    avatarSelectPlaceholder: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    avatarSelectPlaceholderText: {
        fontSize: 12,
        color: theme.colors.primary,
        marginTop: 6,
        fontWeight: '600',
    },
    switchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: '#f1f3f5',
        marginTop: 8,
        marginBottom: 16,
    },
    switchLabelContainer: {
        flex: 1,
        paddingRight: 12,
    },
    switchTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    switchSubtitle: {
        fontSize: 12,
        color: theme.colors.textSecondary,
        marginTop: 4,
        lineHeight: 16,
    },
    applyHeader: {
        marginBottom: 20,
    },
    applyTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 8,
    },
    applySubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 20,
    },
    applyBenefitList: {
        marginVertical: 15,
    },
    applyBenefitItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    applyBenefitIcon: {
        marginRight: 12,
        marginTop: 2,
    },
    applyBenefitText: {
        flex: 1,
    },
    applyBenefitTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 4,
    },
    applyBenefitDesc: {
        fontSize: 13,
        color: theme.colors.textSecondary,
        lineHeight: 18,
    },
    divider: {
        height: 1,
        backgroundColor: theme.colors.border,
        marginVertical: 20,
    },
    filePickerBox: {
        borderWidth: 2,
        borderColor: theme.colors.border,
        borderStyle: 'dashed',
        borderRadius: 12,
        paddingVertical: 24,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.background,
        marginBottom: 20,
    },
    filePickerBoxActive: {
        borderColor: theme.colors.primary,
        backgroundColor: '#f0f7ff',
        borderStyle: 'solid',
    },
    pickerPlaceholder: {
        alignItems: 'center',
    },
    pickerTextBold: {
        fontSize: 15,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 4,
    },
    pickerTextSubtitle: {
        fontSize: 12,
        color: '#888888',
    },
    selectedFileWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
    },
    fileDetails: {
        flex: 1,
        marginLeft: 12,
    },
    fileName: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 2,
    },
    fileSize: {
        fontSize: 12,
        color: theme.colors.textSecondary,
    },
    btnChangeFile: {
        backgroundColor: theme.colors.white,
        borderWidth: 1,
        borderColor: theme.colors.primary,
        borderRadius: 6,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    btnChangeFileText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: theme.colors.primary,
    },
    btnPrimary: {
        backgroundColor: theme.colors.primary,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 8,
        width: '100%',
    },
    btnPrimaryDisabled: {
        backgroundColor: theme.colors.border,
    },
    btnPrimaryText: {
        color: theme.colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    btnSecondary: {
        backgroundColor: theme.colors.white,
        borderWidth: 1,
        borderColor: theme.colors.border,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 8,
        width: '100%',
        marginTop: 12,
    },
    btnSecondaryText: {
        color: theme.colors.text,
        fontSize: 16,
        fontWeight: 'bold',
    },
    statusHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    statusMainLabel: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 16,
    },
    statusBadgeText: {
        color: theme.colors.white,
        fontSize: 12,
        fontWeight: 'bold',
    },
    statusMessageCard: {
        backgroundColor: theme.colors.background,
        borderLeftWidth: 4,
        borderRadius: 6,
        padding: 16,
        marginBottom: 20,
    },
    statusMessageText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 20,
    },
    submittedCvCard: {
        backgroundColor: theme.colors.white,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 8,
        padding: 16,
        marginBottom: 16,
    },
    submittedCvTitle: {
        fontSize: 13,
        fontWeight: 'bold',
        color: '#888888',
        marginBottom: 8,
    },
    submittedFileRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.background,
        borderRadius: 6,
        padding: 12,
        marginBottom: 8,
    },
    submittedFileName: {
        flex: 1,
        marginLeft: 10,
        fontSize: 14,
        color: theme.colors.primary,
        fontWeight: '500',
    },
    submittedDateText: {
        fontSize: 12,
        color: '#888888',
        textAlign: 'right',
    },
    applyLoadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 40,
    },
    applyLoadingText: {
        marginTop: 10,
        fontSize: 14,
        color: theme.colors.textSecondary,
    },
    illustrationWrapper: {
        marginBottom: 20,
        backgroundColor: '#e8f5e9',
        width: 120,
        height: 120,
        borderRadius: 60,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
    },
});

export default { ...GlobalStyles, ...localStyles };
