import { StyleSheet } from "react-native";
import GlobalStyles from "../../styles/Styles";
import theme from "../../styles/theme";

const localStyles = StyleSheet.create({
    avatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginRight: 12,
    },
    userName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginLeft: 5,
    },
    bannerContainer: {
        borderRadius: 12,
        padding: 20,
        marginLeft: 20,
        marginRight: 20,
        marginTop: 5,
    },
    bannerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    bannerSubtitle: {
        fontSize: 14,
    },
    sectionContainer: {
        marginTop: 30,
        paddingHorizontal: 20,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 15,
    },
    categoryItem: {
        backgroundColor: theme.colors.white,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 20,
        marginRight: 12,

    },
    categoryText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    categoryItemSelected: {
        backgroundColor: theme.colors.primary,
        borderColor: theme.colors.primary,
    },
    categoryTextSelected: {
        color: theme.colors.white,
        fontWeight: 'bold',
    },
    cardContainer: {
        marginBottom: 20,
        backgroundColor: theme.colors.white,
        marginLeft: 20,
        marginRight: 20,
    },
    cardContent: {
        marginTop: 10,
    },
    courseTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 5,
    },

    courseInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    courseInstructor: {
        fontSize: 14,
        color: theme.colors.textSecondary,
    },
    coursePrice: {
        fontSize: 15,
        fontWeight: 'bold',
        color: theme.colors.white,
    },
    courseRating: {
        fontSize: 14,
        fontWeight: 'bold',

    },
    courseLessons: {
        fontSize: 14,
        color: theme.colors.textSecondary,
    },
    priceBadge: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: theme.colors.primary,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,

    },
    priceBadgeText: {
        color: theme.colors.white,
        fontWeight: 'bold',
        fontSize: 14,
    },
    myCoursesHeader: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 15,
        backgroundColor: theme.colors.background,
    },
    myCoursesTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 8,
    },
    myCoursesSubtitle: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 20,
    },
    myCourseList: {
        paddingHorizontal: 20,
        paddingBottom: 20,
    },
    myCourseCard: {
        backgroundColor: theme.colors.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: theme.colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    myCourseHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    myCourseImage: {
        width: 70,
        height: 70,
        borderRadius: 12,
        marginRight: 12,
    },
    myCourseInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    myCourseTitleText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 4,
        lineHeight: 22,
    },
    myCourseInstructorText: {
        fontSize: 13,
        color: theme.colors.textSecondary,
    },
    myCourseChevron: {
        marginLeft: 8,
    },
    progressSection: {
        marginTop: 4,
    },
    progressLabelRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    progressLabelText: {
        fontSize: 13,
        color: theme.colors.textSecondary,
    },
    progressPercentText: {
        fontSize: 13,
        fontWeight: 'bold',
        color: theme.colors.primary,
    },
    progressBarTrack: {
        height: 6,
        backgroundColor: theme.colors.border,
        borderRadius: 3,
        width: '100%',
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: theme.colors.primary,
        borderRadius: 3,
    },
    detailBannerImage: {
        width: '100%',
        height: 220,
        resizeMode: 'cover',
    },
    card: {
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },

    row: {
        flexDirection: 'row',
        alignItems: 'center',
    },

    h1: {
        fontSize: 22,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    h2: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    title: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.text,
    },
    body: {
        fontSize: 15,
        color: theme.colors.textSecondary,
        lineHeight: 22,
    },
    small: {
        fontSize: 13,
        color: '#888888',
    },
    avatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: theme.colors.border,
    },
    segmentedContainer: {
        flexDirection: 'row',
        backgroundColor: theme.colors.border,
        borderRadius: 12,
        padding: 4,
        marginHorizontal: 20,
        marginBottom: 16,
        marginTop: 10,
    },
    segmentButton: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
    },
    segmentButtonActive: {
        backgroundColor: theme.colors.white,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    segmentText: {
        fontSize: 14,
        fontWeight: '600',
        color: theme.colors.textSecondary,
    },
    segmentTextActive: {
        color: theme.colors.primary,
        fontWeight: 'bold',
    },
    reviewSectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginTop: 20,
        marginBottom: 10,
        marginLeft: 20,
        marginRight: 20,
    },
    reviewContainer: {
        marginLeft: 20,
        marginRight: 20,
        marginBottom: 16,
    },
    reviewItem: {
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
    },
    reviewUserAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        marginRight: 10,
    },
    reviewUserRole: {
        fontSize: 10,
        color: theme.colors.primary,
        fontWeight: 'bold',
        backgroundColor: '#e8f0fe',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        alignSelf: 'flex-start',
        marginTop: 2,
    },
    reviewRatingStars: {
        flexDirection: 'row',
        marginVertical: 4,
    },
    reviewCommentText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 20,
        marginTop: 4,
    },
    reviewDateText: {
        fontSize: 11,
        color: '#999999',
        marginTop: 4,
    },
    noReviewsText: {
        fontSize: 14,
        color: '#888888',
        textAlign: 'center',
        paddingVertical: 20,
    },
    ratingSelectorContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 12,
    },
    writeReviewTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 8,
        textAlign: 'center',
    },
    reviewTextInput: {
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 8,
        padding: 12,
        fontSize: 14,
        minHeight: 80,
        textAlignVertical: 'top',
        backgroundColor: theme.colors.background,
        marginBottom: 12,
    },
    btnSubmitReview: {
        alignSelf: 'flex-end',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 30,
        marginTop: 8,
        backgroundColor: theme.colors.primary,

        shadowColor: theme.colors.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    btnSubmitReviewDisabled: {
        backgroundColor: '#a0c4ff',
        shadowOpacity: 0,
        elevation: 0,
    },
    btnSubmitReviewText: {
        color: theme.colors.white,
        fontSize: 15,
        fontWeight: 'bold',
    },
    formContainer: {
        padding: 20,
        backgroundColor: theme.colors.white,
        borderRadius: 12,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    formGroup: {
        marginBottom: 18,
    },
    formLabel: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.colors.textSecondary,
        marginBottom: 6,
    },
    categorySelector: {
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 14,
        backgroundColor: theme.colors.white,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    categorySelectorText: {
        fontSize: 15,
        color: theme.colors.text,
    },
    categoryPlaceholderText: {
        fontSize: 15,
        color: '#adb5bd',
    },
    imagePickerBox: {
        borderWidth: 2,
        borderColor: theme.colors.border,
        borderStyle: 'dashed',
        borderRadius: 12,
        height: 180,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.colors.background,
        marginBottom: 20,
        overflow: 'hidden',
    },
    imagePickerActive: {
        borderColor: theme.colors.primary,
        backgroundColor: '#f0f7ff',
        borderStyle: 'solid',
    },
    imagePreview: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    lessonVideoContainer: {
        width: '100%',
        height: 220,
        backgroundColor: '#000000',
        borderRadius: 12,
        overflow: 'hidden',
        marginBottom: 16,
    },
    lessonVideo: {
        width: '100%',
        height: '100%',
    },
    lessonMetaRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginVertical: 12,
        paddingHorizontal: 4,
    },
    lessonTagContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        flex: 1,
    },
    lessonTagPill: {
        backgroundColor: '#e8f0fe',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginRight: 8,
        marginBottom: 6,
    },
    lessonTagText: {
        fontSize: 12,
        color: theme.colors.primary,
        fontWeight: 'bold',
    },
    lessonLikeBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f2f5',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
    },
    lessonLikeBtnActive: {
        backgroundColor: '#ffebee',
    },
    lessonLikeText: {
        fontSize: 13,
        fontWeight: 'bold',
        color: '#65676b',
        marginLeft: 6,
    },
    lessonLikeTextActive: {
        color: theme.colors.danger,
    },
    btnCompleteLesson: {
        backgroundColor: theme.colors.success,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        borderRadius: 10,
        width: '100%',
        marginVertical: 16,
        shadowColor: theme.colors.success,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
    },
    btnCompleteLessonActive: {
        backgroundColor: '#e2f0d9',
        borderWidth: 1,
        borderColor: theme.colors.success,
        shadowOpacity: 0,
        elevation: 0,
    },
    btnCompleteLessonText: {
        color: theme.colors.white,
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    btnCompleteLessonTextActive: {
        color: theme.colors.success,
    },
    commentSectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginTop: 20,
        marginBottom: 12,
    },
    commentItem: {
        flexDirection: 'row',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f2f5',
    },
    commentAvatar: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: theme.colors.border,
        marginRight: 10,
    },
    commentContentContainer: {
        flex: 1,
        backgroundColor: '#f0f2f5',
        borderRadius: 12,
        padding: 12,
    },
    commentUserRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    commentUserName: {
        fontSize: 14,
        fontWeight: 'bold',
        color: theme.colors.text,
    },
    commentDate: {
        fontSize: 11,
        color: '#888888',
    },
    commentText: {
        fontSize: 14,
        color: theme.colors.textSecondary,
        lineHeight: 18,
    },
    commentBarContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: theme.colors.border,
        backgroundColor: theme.colors.white,
        paddingHorizontal: 12,
        paddingVertical: 8,
    },
    commentBarInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#ced4da',
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 8,
        fontSize: 14,
        maxHeight: 80,
        backgroundColor: theme.colors.secondary,
        marginRight: 10,
    },
    commentBarSendBtn: {
        width: 38,
        height: 38,
        borderRadius: 19,
        backgroundColor: theme.colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    commentBarSendBtnDisabled: {
        backgroundColor: '#e4e6eb',
    },
    replyCommentItem: {
        flexDirection: 'row',
        paddingVertical: 10,
        marginLeft: 40,
        marginTop: 6,
        backgroundColor: theme.colors.secondary,
        borderRadius: 12,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#f0f2f5',
    },
    commentReplyBtn: {
        marginLeft: 10,
    },
    commentReplyBtnText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: theme.colors.primary,
    },
    replyingBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#e8f0fe',
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderTopWidth: 1,
        borderTopColor: '#d2e3fc',
    },
    replyingText: {
        fontSize: 12,
        color: theme.colors.primary,
        fontWeight: '500',
    },
});

export default { ...GlobalStyles, ...localStyles };
