"""
Django settings for ecourse project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import cloudinary

# Đường dẫn gốc của project
BASE_DIR = Path(__file__).resolve().parent.parent

# Cấu hình lưu trữ file tĩnh cho ckeditor
MEDIA_ROOT = '%s/courses/static/' % BASE_DIR

# Khóa bảo mật của Django
SECRET_KEY = 'django-insecure-knk8f1uc392i*ty3y(hox-)&47tn-6lo-s58=#1he$-1lpgm$+'

# Chế độ Debug (True cho dev, False cho production)
DEBUG = True

ALLOWED_HOSTS = ['*']

# Danh sách các app đã cài đặt
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses.apps.CoursesConfig',
    'drf_yasg',            # App tạo tài liệu API (Swagger)
    'rest_framework',      # Django REST Framework
    'oauth2_provider',     # Thư viện cấp quyền OAuth2
    'django_filters',      # Thư viện lọc dữ liệu cho API
]

# Cấu hình REST Framework
REST_FRAMEWORK = {
    # Mặc định sử dụng xác thực OAuth2
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    # Mặc định sử dụng bộ lọc DjangoFilter
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# Các middleware của hệ thống
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'ecourse.middlewares.OAuth2InjectCredentialsMiddleware', # Custom middleware tự động chèn OAuth2 credentials
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecourse.urls'

# Model User tùy chỉnh thay vì mặc định
AUTH_USER_MODEL = 'courses.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecourse.wsgi.application'

# Cấu hình kết nối Cơ sở dữ liệu (Database)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecoursedb',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': ''  # mặc định localhost
    }
}

# Cấu hình kiểm tra tính hợp lệ của mật khẩu
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'courses.validators.PasswordLengthValidator'},
    {'NAME': 'courses.validators.PasswordWhitespaceValidator'},
    {'NAME': 'courses.validators.PasswordAsciiValidator'},
]

# Cấu hình kiểm tra tính hợp lệ của username
CUSTOM_USERNAME_VALIDATORS = [
    {'NAME': 'courses.validators.UsernameLengthValidator'},
    {'NAME': 'courses.validators.UsernameWhitespaceValidator'},
    {'NAME': 'courses.validators.UsernameAsciiValidator'},
]

# Ngôn ngữ và Múi giờ
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = False

STATIC_URL = 'static/'

# Load các biến môi trường từ file .env
load_dotenv(BASE_DIR / '.env')

# Cấu hình Cloudinary (Lưu trữ ảnh/video)
cloudinary.config(
    cloud_name=os.getenv('CLOUD_NAME'),
    api_key=os.getenv('API_KEY'),
    api_secret=os.getenv('API_SECRET')
)

BASE_DOMAIN = os.getenv('BASE_DOMAIN', 'http://localhost:8000')

# Cấu hình thanh toán tiền mặt/chuyển khoản
CASH_CONFIG = {
    'BANK_ACCOUNT': os.getenv('ACCOUNT_NUMBER', ''),
    'BANK_NAME': os.getenv('BANK_NAME', ''),
    'ACCOUNT_NAME': os.getenv('NAME', '')
}

# ==========================================
# 1. CẤU HÌNH MOMO
# ==========================================
MOMO_CONFIG = {
    'PARTNER_CODE': os.getenv('MOMO_PARTNER_CODE', ''),
    'ACCESS_KEY': os.getenv('MOMO_ACCESS_KEY', ''),
    'SECRET_KEY': os.getenv('MOMO_SECRET_KEY', ''),
    'ENDPOINT': os.getenv('MOMO_ENDPOINT', 'https://test-payment.momo.vn/v2/gateway/api/create'),
    'RETURN_URL': f"{BASE_DOMAIN}/webhooks/momo/",
    'NOTIFY_URL': os.getenv('MOMO_NOTIFY_URL', f"{BASE_DOMAIN}/webhooks/momo/"),
}

# ==========================================
# 2. CẤU HÌNH ZALOPAY
# ==========================================
ZALOPAY_CONFIG = {
    'APP_ID': os.getenv('ZALOPAY_APP_ID', ''),
    'KEY1': os.getenv('ZALOPAY_KEY1', ''),
    'KEY2': os.getenv('ZALOPAY_KEY2', ''),
    'ENDPOINT': os.getenv('ZALOPAY_ENDPOINT', 'https://sb-openapi.zalopay.vn/v2/create'),
    'REDIRECT_URL': f"{BASE_DOMAIN}/webhooks/zalopay/",
    'CALLBACK_URL': os.getenv('ZALOPAY_CALLBACK_URL', f"{BASE_DOMAIN}/webhooks/zalopay/"),
}

# ==========================================
# 3. CẤU HÌNH STRIPE
# ==========================================
STRIPE_CONFIG = {
    'PUBLISHABLE_KEY': os.getenv('STRIPE_PUBLIC_KEY', ''),
    'SECRET_KEY': os.getenv('STRIPE_SECRET_KEY', ''),
    'WEBHOOK_SECRET': os.getenv('STRIPE_WEBHOOK_SECRET', ''),
    'RETURN_URL': f"{BASE_DOMAIN}/webhooks/stripe/",
    'CANCEL_URL': f"{BASE_DOMAIN}/webhooks/stripe/"
}

# ==========================================
# 4. CẤU HÌNH PAYPAL
# ==========================================
PAYPAL_CONFIG = {
    'MODE': 'sandbox' if os.getenv('PAYPAL_IS_SANDBOX', 'True') == 'True' else 'live',
    'CLIENT_ID': os.getenv('PAYPAL_CLIENT_ID', ''),
    'CLIENT_SECRET': os.getenv('PAYPAL_SECRET', ''),
    'RETURN_URL': f"{BASE_DOMAIN}/webhooks/paypal/",
    'CANCEL_URL': f"{BASE_DOMAIN}/webhooks/paypal/"
}

# ==========================================
# 5. CẤU HÌNH OAUTH2 SECURE CREDENTIALS
# ==========================================
OAUTH2_CLIENT_ID = os.getenv('OAUTH2_CLIENT_ID', '')
OAUTH2_CLIENT_SECRET = os.getenv('OAUTH2_CLIENT_SECRET', '')
