# Generated by Django 6.0.4 on 2026-05-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_enrollment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='intro_video',
        ),
    ]
