# Generated by Django 6.0.4 on 2026-05-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_intro_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Cho phép xem thử bài học miễn phí trước khi đăng ký khóa học'),
        ),
    ]
