"""
Django settings for ecourse project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import cloudinary.api

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = '%s/courses/static/' % BASE_DIR
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-knk8f1uc392i*ty3y(hox-)&47tn-6lo-s58=#1he$-1lpgm$+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'courses.apps.CoursesConfig',
    'drf_yasg',
    'rest_framework',
    'oauth2_provider',
    'django_filters',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecourse.urls'

AUTH_USER_MODEL = 'courses.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecourse.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecoursedb',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': ''  # mặc định localhost
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Cloudinary
cloudinary.config(
    cloud_name="db4bjqp4f",
    api_key="644913513335787",
    api_secret="3GyWpk9k_hVPbrHy1blNOyjIwyA"
)
load_dotenv()

BASE_DOMAIN = os.getenv('BASE_DOMAIN', 'http://localhost:8000')

# ==========================================
# 1. CẤU HÌNH MOMO
# ==========================================
MOMO_CONFIG = {
    'PARTNER_CODE': os.getenv('MOMO_PARTNER_CODE', ''),
    'ACCESS_KEY': os.getenv('MOMO_ACCESS_KEY', ''),
    'SECRET_KEY': os.getenv('MOMO_SECRET_KEY', ''),
    'ENDPOINT': os.getenv('MOMO_ENDPOINT', 'https://test-payment.momo.vn/v2/gateway/api/create'),
    'RETURN_URL': f"{BASE_DOMAIN}/payments/momo-return/",
    'NOTIFY_URL': os.getenv('MOMO_NOTIFY_URL', f"{BASE_DOMAIN}/payments/momo-ipn/"),
}

# ==========================================
# 2. CẤU HÌNH ZALOPAY
# ==========================================
ZALOPAY_CONFIG = {
    'APP_ID': os.getenv('ZALOPAY_APP_ID', ''),
    'KEY1': os.getenv('ZALOPAY_KEY1', ''),
    'KEY2': os.getenv('ZALOPAY_KEY2', ''),
    'ENDPOINT': os.getenv('ZALOPAY_ENDPOINT', 'https://sb-openapi.zalopay.vn/v2/create'),
    'REDIRECT_URL': f"{BASE_DOMAIN}/payments/zalopay-return/",
    'CALLBACK_URL': os.getenv('ZALOPAY_CALLBACK_URL', f"{BASE_DOMAIN}/payments/zalopay-callback/"),
}

# ==========================================
# 3. CẤU HÌNH STRIPE
# ==========================================
STRIPE_CONFIG = {
    'PUBLISHABLE_KEY': os.getenv('STRIPE_PUBLIC_KEY', ''),
    'SECRET_KEY': os.getenv('STRIPE_SECRET_KEY', ''),
    'WEBHOOK_SECRET': os.getenv('STRIPE_WEBHOOK_SECRET', ''),
    'RETURN_URL': f"{BASE_DOMAIN}/payments/stripe-return/",
    'CANCEL_URL': f"{BASE_DOMAIN}/payments/stripe-cancel/"
}

# ==========================================
# 4. CẤU HÌNH PAYPAL
# ==========================================
PAYPAL_CONFIG = {
    'MODE': 'sandbox' if os.getenv('PAYPAL_IS_SANDBOX', 'True') == 'True' else 'live',
    'CLIENT_ID': os.getenv('PAYPAL_CLIENT_ID', ''),
    'CLIENT_SECRET': os.getenv('PAYPAL_SECRET', ''),
    'RETURN_URL': f"{BASE_DOMAIN}/payments/paypal-return/",
    'CANCEL_URL': f"{BASE_DOMAIN}/payments/paypal-cancel/"
}
