# Generated by Django 6.0.4 on 2026-05-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_instructorapplication_cv_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_minutes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Thời lượng video (tính bằng giây)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_duration_video',
            field=models.PositiveIntegerField(default=0, help_text='Tổng số giây video'),
        ),
    ]
