# Generated by Django 6.0.4 on 2026-05-09 02:24

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_video_minutes_lesson_video_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorapplication',
            name='cv_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='cv_file'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='image/upload/v1765436438/shtnr60mecp057e2uctk.jpg', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
